import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        cairo: ["var(--font-cairo)", "Cairo", "sans-serif"],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-space-grotesk)", "var(--font-inter)", "system-ui", "sans-serif"],
        medex: ["var(--font-montserrat)", "var(--font-inter)", "system-ui", "sans-serif"],
      },
      colors: {
        medex: {
          red: "#18446e",
          "red-dark": "#123554",
          "red-light": "#2a5f93",
          dark: "#1a1a2e",
          gray: "#6b7280",
          light: "#f8f9fa",
          mist: "#f1f5f9",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "hsl(var(--primary-foreground))",
          hover: "var(--color-primary-hover)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "hsl(var(--secondary-foreground))",
          hover: "var(--color-secondary-hover)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        /** Public marketing surface only — do not use in dashboards (shadcn uses `primary` / `background`). */
        mds: {
          background: "#faf9f7",
          surface: "#faf9f7",
          "surface-bright": "#ffffff",
          "surface-dim": "#e8e4df",
          "surface-variant": "#f0ece6",
          "surface-container": "#f5f2ed",
          "surface-container-low": "#faf8f5",
          "surface-container-lowest": "#ffffff",
          "surface-container-high": "#ebe6df",
          "surface-container-highest": "#e2dcd4",
          "surface-tint": "#1345D6",
          primary: "#1345D6",
          "on-primary": "#ffffff",
          "primary-container": "#3D74F2",
          "on-primary-container": "#f5f8ff",
          "primary-fixed": "#d6e4ff",
          "on-primary-fixed": "#08183d",
          "primary-fixed-dim": "#a8c4f5",
          "on-primary-fixed-variant": "#0B2F8C",
          "inverse-primary": "#a8c4f5",
          secondary: "#5c4a3a",
          "on-secondary": "#ffffff",
          "secondary-container": "#f0ece6",
          "on-secondary-container": "#3d3228",
          "secondary-fixed": "#f0ece6",
          "on-secondary-fixed": "#1a1510",
          "secondary-fixed-dim": "#d4cfc8",
          "on-secondary-fixed-variant": "#44382e",
          tertiary: "#0E7DD1",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#2C97EA",
          "on-tertiary-container": "#f5fbff",
          "tertiary-fixed": "#d3ecff",
          "on-tertiary-fixed": "#00263d",
          "tertiary-fixed-dim": "#a3d4f5",
          "on-tertiary-fixed-variant": "#0A5A99",
          error: "#ba1a1a",
          "error-container": "#ffdad6",
          "on-error": "#ffffff",
          "on-error-container": "#93000a",
          "on-background": "#1a1a1f",
          "on-surface": "#1a1a1f",
          "on-surface-variant": "#4a4540",
          outline: "#7a756e",
          "outline-variant": "#d4cfc8",
          "inverse-surface": "#2f2e33",
          "inverse-on-surface": "#f5f2ed",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1.25rem",
        "2xl": "1.5rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
